<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\config.props" />

    <PropertyGroup>
        <AssemblyName>TnmsExtendableTargeting</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ModSharp.Sharp.Shared" Version="2.1.121" ExcludeAssets="runtime" />
        <ProjectReference Include="..\TnmsExtendableTargeting.Shared\TnmsExtendableTargeting.Shared.csproj" Private="false" ExcludeAssets="all" />
    </ItemGroup>

</Project>
